In [20]:
import geopandas
gdf = geopandas.read_file('../data/PROT_HISTORICAL_INCIDENTS_SP.geojson')
gdf

,FIRE_NUMBER,FIRE_YEAR,IGNITION_DATE,FIRE_CAUSE,FIRE_LABEL,FIRE_CENTRE,ZONE,FIRE_ID,FIRE_TYPE,GEOGRAPHIC_DESCRIPTION,LATITUDE,LONGITUDE,CURRENT_SIZE,FEATURE_CODE,OBJECTID,SE_ANNO_CAD_DATA,fme_feature_type,geometry
0,K50756,2013,20130818091300,Person,2013-K50756,5.0,5.0,500756,Nuisance Fire,Darke Lake,49.7118,-119.8661,0.009,JA70003000,14704564,None,WHSE_LAND_AND_NATURAL_RESOURCE.PROT_HISTORICAL...,POINT (-119.86608 49.71180)
1,G90349,2004,20040717150300,Lightning,2004-G90349,4.0,9.0,400349,Fire,Thetlaandoa Creek,59.5515,-121.4590,1.000,JA70003000,14704565,None,WHSE_LAND_AND_NATURAL_RESOURCE.PROT_HISTORICAL...,POINT (-121.45900 59.55150)
2,G13106,2018,20181010155200,Unknown,2018-G13106,4.0,1.0,403106,Smoke Chase,salmon valley,54.2382,-122.6071,NaN,JA70003000,14704566,None,WHSE_LAND_AND_NATURAL_RESOURCE.PROT_HISTORICAL...,POINT (-122.60712 54.23817)
3,K61162,2002,20020923124900,Unknown,2002-K61162,5.0,6.0,501162,Smoke Chase,S End of Peter Hope Lk.,50.2859,-120.3123,NaN,JA70003000,14704567,None,WHSE_LAND_AND_NATURAL_RESOURCE.PROT_HISTORICAL...,POINT (-120.31232 50.28593)
4,N70289,2002,20020723154000,Lightning,2002-N70289,6.0,7.0,600289,Fire,Above Ainsworth,49.7512,-116.9222,0.009,JA70003000,14704568,None,WHSE_LAND_AND_NATURAL_RESOURCE.PROT_HISTORICAL...,POINT (-116.92217 49.75123)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187142,K60287,1998,19980729,Lightning,1998-K60287,5.0,6.0,287,Fire,Dry Lake #3,49.6420,-120.6655,0.100,JA70003000,14888926,None,WHSE_LAND_AND_NATURAL_RESOURCE.PROT_HISTORICAL...,POINT (-120.66550 49.64200)
187143,K60288,1998,19980728,Lightning,1998-K60288,5.0,6.0,288,Fire,AP Ranch,49.7584,-120.6811,0.100,JA70003000,14888927,None,WHSE_LAND_AND_NATURAL_RESOURCE.PROT_HISTORICAL...,POINT (-120.68108 49.75837)
187144,K60302,1998,19980728,Lightning,1998-K60302,5.0,6.0,302,Fire,S of Airport Ranch,49.7384,-120.6289,0.100,JA70003000,14888928,None,WHSE_LAND_AND_NATURAL_RESOURCE.PROT_HISTORICAL...,POINT (-120.62892 49.73837)
187145,K60341,1998,19980731,Lightning,1998-K60341,5.0,6.0,341,Fire,Pimanus Hill,50.3798,-121.1803,0.100,JA70003000,14888929,None,WHSE_LAND_AND_NATURAL_RESOURCE.PROT_HISTORICAL...,POINT (-121.18033 50.37983)
187146,K60350,1998,19980731,Lightning,1998-K60350,5.0,6.0,350,Fire,Rey Lake,50.3413,-120.7403,0.200,JA70003000,14888930,None,WHSE_LAND_AND_NATURAL_RESOURCE.PROT_HISTORICAL...,POINT (-120.74033 50.34133)

In [47]:
import pandas as pd
# Filter out non-dates, map dates to datetimes, normalize all dates to midnight, convert all dates to unix timestamps
gdf['IGNITION_DATE'] = gdf['IGNITION_DATE'].dropna().map(pd.to_datetime).dt.normalize()
# Group by fire centre, zone and ignition date and get counts
out = gdf[['FIRE_CENTRE', 'ZONE', 'IGNITION_DATE']].groupby(['FIRE_CENTRE', 'ZONE', 'IGNITION_DATE']).size()
# Put groupby dataframe into a new frame without multi index so we get flat rows
out = out.to_frame(name = 'COUNT').reset_index()
out

     FIRE_CENTRE  ZONE IGNITION_DATE  COUNT
0            2.0   0.0    1969-12-31   7321
1            2.0   1.0    1970-01-01   6111
2            2.0   2.0    1969-12-31      1
3            2.0   2.0    1970-01-01    574
4            2.0   3.0    1970-01-01   3180
..           ...   ...           ...    ...
142          7.0  20.0    1970-01-01    348
143          7.0  21.0    1970-01-01    109
144          7.0  23.0    1970-01-01    226
145          7.0  24.0    1970-01-01    217
146          7.0  60.0    1970-01-01      1

[147 rows x 4 columns]